### PR TITLE
Fix file upload completion event detection

### PR DESCRIPTION
**Pull request by dtitov**
Addresses this issue: https://github.com/NBISweden/LocalEGA/pull/316#issuecomment-405835826

### CODE REVIEW

**Comment by blankdots** [comment]
Could we have a bumped version of this:
e.g.: `<version>0.0.2-SNAPSHOT</version>` instead of `0.0.1` ?

Should have explained this proposal, I think we should have a new version even though it is just a bug, it will be easier to see if the Docker image gets updated with the right `jar`.

**Comment by dtitov** [comment]
Sure, why not. Should we increase the last number every next PR?

**Comment by blankdots** [comment]
We are not doing it for the LocalEGA, however I do think it is a good practice + this adds some memory optimisations, so I view that a big deal has changed.

**Comment by blankdots** [comment]
I know it is not part of this issue, and that I am nitpicking:
On this line I would check if `.getStatusCode()` is `200` before getting the body, just a good practice and also good idea before getting the body.
https://github.com/NBISweden/LocalEGA-inbox/blob/feature/handle-file-operation/src/main/java/se/nbis/lega/inbox/sftp/CredentialsProvider.java#L42

**Comment by blankdots** [comment]
Should it not check vis some sort of hashing alg that the file was modified https://github.com/NBISweden/LocalEGA-inbox/blob/feature/handle-file-operation/src/main/java/se/nbis/lega/inbox/sftp/InboxSftpEventListener.java#L60 ?

**Comment by dtitov** [comment]
1. Added status code check.
2. Digest verification is not required as per discussion with Fred.

**Review by blankdots — APPROVED** [review]
ok, I approve.
Please Also make a task about adding Blowfish encryption to the auth (if I remember correctly all should be there md5, sha etc.)

**Comment by dtitov** [comment]
I will, thanks.

**Comment by dtitov** [comment]
`nbisweden/ega-mina-inbox` pushed. I'll add auto-push on successful PR merge to the next PR.

**Pull request merged**
